version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: pomodoro
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: node-app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_NAME: pomodoro

volumes:
  postgres_data:
