version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: pomodoro
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

volumes:
  postgres-data:
