INSERT INTO "user" (
        username,
        email,
        password_hash,
        created_at,
        updated_at
    )
VALUES (
        'testuser1',
        'testuser1@example.com',
        'passwordhash1',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'testuser2',
        'testuser2@example.com',
        'passwordhash2',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'testuser3',
        'testuser3@example.com',
        'passwordhash3',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'testuser4',
        'testuser4@example.com',
        'passwordhash4',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'testuser5',
        'testuser5@example.com',
        'passwordhash5',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );
INSERT INTO configuration (
        work_interval,
        short_break,
        long_break,
        long_break_interval,
        created_at,
        updated_at,
        user_id
    )
VALUES (
        25,
        5,
        15,
        4,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        1
    ),
    -- For testuser1
    (
        25,
        5,
        15,
        4,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        2
    ),
    -- For testuser2
    (
        25,
        5,
        15,
        4,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        3
    ),
    -- For testuser3
    (
        25,
        5,
        15,
        4,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        4
    ),
    -- For testuser4
    (
        25,
        5,
        15,
        4,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        5
    );
-- For testuser5